<?php

return [
    '0' => 'Mensagem não definida',
    '1' => 'Usuário ou senha incorretos',
    '2' => 'Favor inserir o email',
    '3' => 'Favor inserir a senha',
    '4' => 'Favor inserir o nome',
    '5' => 'Favor inserir o registro do professor',
    '6' => 'Favor inserir a data de nascimento',
    '7' => 'Favor inserir o número do whatsapp',
    '8' => 'Falha ao cadastrar usuário',
    '9' => 'Usuário já cadastrado',
    '10' => 'Número de Whatsapp já cadastrado',
    '11' => 'Número de registro do professor já cadastrado',
    '12' => 'Número de matricula do aluno já cadastrado',
    '13' => 'Email já cadastrado',
    '14' => 'Usuário não existe',
    '15' => 'Favor informar o título do Quiz',
    '16' => 'Favor informar a disciplina do Quiz',
    '17' => 'A quantidade de questões está incorreta',
    '18' => 'As questões devem conter 4 respostas',
    '19' => 'Favor informar o tempo de duração do quiz',
    '20' => 'As questões devem haver apenas 1 reposta correta',
    '21' => 'As questões devem haver ao menos 1 resposta correta',
    '22' => 'Falha ao cadastrar Quiz',
];
